using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ColabBoard.Domain.Entities;

public class Stroke : BaseEntity
{
    // The ID generated by Excalidraw client
    [Required]
    public string ElementId { get; set; } = string.Empty;

    // The full JSON object of the element attributes
    [Column(TypeName = "jsonb")]
    [Required]
    public string ElementAttributes { get; set; } = "{}";
    
    [Required]
    public Room Room { get; set; }
}